### ISSUE TITLE
Configuration Validation Fails

### ISSUE THREAD

**Issue by Bjsulla** [easink/hass.aioheos.media_player#1]
I get the following in the error log when checking the configuration when running Home Assistant 0.42.2

`17-04-12 18:03:40 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.media_player.heos. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/loader.py", line 141, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/media_player/heos.py", line 35, in <module>
    from aioheos import AioHeos # pylint: disable=wrong-import-position
ImportError: No module named 'aioheos'`

Can you please advice on how to get this working?

**Comment by easink** [comment]
For some reason the requirements isnt being installed by home assistant I
dont know why. But you can install the requirements manually:

>  pip3 install '
https://github.com/easink/aioheos/archive/v0.1.3.zip#heos==0.1.3'



2017-04-12 18:07 GMT+02:00 Bjsulla <notifications@github.com>:

**Comment by Bjsulla** [comment]
Thank you aioheos is now installed and listed when typing "pip3 freeze" as aioheos==0.1.3 but I stil get the following in the home-assistant.log after restarting home assistant

> 17-04-12 22:41:17 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.media_player.heos. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/loader.py", line 141, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/media_player/heos.py", line 35, in <module>
    from aioheos import AioHeos # pylint: disable=wrong-import-position
ImportError: No module named 'aioheos'
17-04-12 22:41:17 ERROR (MainThread) [homeassistant.loader] Unable to find component media_player.heos

**Comment by easink** [comment]
Hmm, did you install aioheos as a normal user or as root? If as a normal user, try as root.

**Comment by Bjsulla** [comment]
Found it!
I have home assistant running in venv so I uninstalled aioheos and then did the following (for future reference):

`su -s /bin/bash homeassistant
source /srv/homeassistant/bin/activate
pip3 install 'https://github.com/easink/aioheos/archive/v0.1.3.zip#heos==0.1.3'`

And now it is working.
Thank you for your help and keep up the good work I would love to see this in released as a standar home assistant component (tusen,tusen tack!)

**Comment by easink** [comment]
Excellent, nice that its working... =)

Och, tack så mycket!

**Comment by aladin2000** [comment]
Hi Andreas

What I've done  in a BIG Progress  and I report what was wrong !

1) rename directory to custom_component instead of custom_components and 
remove everything excel heos.py

2) put every 'auto discovery' media_player  for chromecast' in comment

--- after that I can see a DATA BOCK  in the UI  showing  the Heos 
Component  . ---> YES


But Now  the status of the player is visible as OFF as my android Heos 
app show the device  is ON

So my questions are : how to reuse the other media_player to use them  
in  the same time as Heos ?

I tried media_player N

How to have extra fonction of Heos  to be seen in the UI data bloc ; 
like playlist, Stations favorites,... rather than to use in the device menu


regards
Aladin

**Comment by Jolanrensen** [comment]
Is it possible to do the same on HASSIO? Normally you can't really install stuff as everything is in a separate docker image

**Comment by Jolanrensen** [comment]
as stated in https://home-assistant.io/developers/code_review_component/, the imports need to be done inside functions, that might be the reason this error occurs. I tried moving it myself, but it's not yet working on hassio

**Comment by Jolanrensen** [comment]
https://github.com/easink/hass.aioheos.media_player/pull/4
