### ISSUE TITLE
Enable Home Assistant SSL generates errors

### ISSUE THREAD

**Issue by Bjsulla** [easink/hass.aioheos.media_player#2]
When enabling https for Home Assistant (https://home-assistant.io/blog/2015/12/13/setup-encryption-using-lets-encrypt) the log file gets filled with these errors, over and over again

> Apr 18 00:10:16 NUC01 hass[1667]: self._sslobj.do_handshake()
Apr 18 00:10:16 NUC01 hass[1667]: ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:600)
Apr 18 00:10:16 NUC01 hass[1667]: 17-04-18 00:10:16 INFO (MainThread) [homeassistant.components.http] Serving /api/websocket t...: False)
Apr 18 00:10:16 NUC01 hass[1667]: 17-04-18 00:10:16 WARNING (MainThread) [asyncio] <_SelectorSslTransport fd=23 read=idle writ...e failed
Apr 18 00:10:16 NUC01 hass[1667]: Traceback (most recent call last):
Apr 18 00:10:16 NUC01 hass[1667]: File "/usr/lib/python3.4/asyncio/selector_events.py", line 727, in _on_handshake
Apr 18 00:10:16 NUC01 hass[1667]: self._sock.do_handshake()
Apr 18 00:10:16 NUC01 hass[1667]: File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
Apr 18 00:10:16 NUC01 hass[1667]: self._sslobj.do_handshake()
Apr 18 00:10:16 NUC01 hass[1667]: ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:600)

**Comment by joostvanmourik** [comment]
Still a lot of WARNINGS in the Log it seems to work but the log gets fileld up much to quickly
